sudo: required
services:
  - docker

before_install:
  - docker build -t bee25141/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bee25141/docker-react npm test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-422728243729"
  bucket_path: "Docker-React"
  on: 
    branch: master

  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY